<<<<<<< HEAD
# stages:
#   data_ingestion:
#     cmd: python src/cnnClassifier/pipeline/stage01_data_ingestion.py
#     deps:
#       - src/cnnClassifier/pipeline/stage01_data_ingestion.py
#       - config/config.yaml
#     outs:
#       - artifacts/data_ingestion/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone

#   prepare_base_model:
#     cmd: python src/cnnClassifier/pipeline/stage02_prepare_base_model.py
#     deps:
#       - src/cnnClassifier/pipeline/stage02_prepare_base_model.py
#       - config/config.yaml
#     params:
#       - IMAGE_SIZE
#       - INCLUDE_TOP
#       - CLASSES
#       - WEIGHTS
#       - LEARNING_RATE
#     outs:
#       - artifacts/prepare_base_model

#   training:
#     cmd: python src/cnnClassifier/pipeline/stage03_training.py
#     deps:
#       - src/cnnClassifier/pipeline/stage03_training.py
#       - config/config.yaml
#       - artifacts/data_ingestion/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone
#       - artifacts/prepare_base_model
#     params:
#       - IMAGE_SIZE
#       - EPOCHS
#       - BATCH_SIZE
#       - AUGMENTATION
#     outs:
#       - model/model.h5
#   evaluation:
#     cmd: python src/cnnClassifier/pipeline/stage04_model_evaluation.py
#     deps:
#       - src/cnnClassifier/pipeline/stage04_model_evaluation.py
#       - config/config.yaml
#       - artifacts/data_ingestion/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone
#       - model/model.h5
#     params:
#       - IMAGE_SIZE
#       - BATCH_SIZE
#     metrics:
#       - scores.json:
#           cache: false



# .dvc/config


# dvc.yaml (Enhanced version)
=======
>>>>>>> 5adff314d02f66028c6e638381928b3ec4252372
stages:
  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/stage01_data_ingestion.py
    deps:
      - src/cnnClassifier/pipeline/stage01_data_ingestion.py
      - config/config.yaml
    outs:
<<<<<<< HEAD
      - artifacts/data_ingestion/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone:
          cache: true
          persist: true
=======
      - artifacts/data_ingestion/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone
>>>>>>> 5adff314d02f66028c6e638381928b3ec4252372

  prepare_base_model:
    cmd: python src/cnnClassifier/pipeline/stage02_prepare_base_model.py
    deps:
      - src/cnnClassifier/pipeline/stage02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
<<<<<<< HEAD
      - artifacts/prepare_base_model:
          cache: true
          persist: true
=======
      - artifacts/prepare_base_model
>>>>>>> 5adff314d02f66028c6e638381928b3ec4252372

  training:
    cmd: python src/cnnClassifier/pipeline/stage03_training.py
    deps:
      - src/cnnClassifier/pipeline/stage03_training.py
      - config/config.yaml
      - artifacts/data_ingestion/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
<<<<<<< HEAD
      - model/model.h5:
          cache: true
          persist: true

=======
      - model/model.h5
>>>>>>> 5adff314d02f66028c6e638381928b3ec4252372
  evaluation:
    cmd: python src/cnnClassifier/pipeline/stage04_model_evaluation.py
    deps:
      - src/cnnClassifier/pipeline/stage04_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone
      - model/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - scores.json:
<<<<<<< HEAD
          cache: false
    plots:
      - plots/training_history.json:
=======
>>>>>>> 5adff314d02f66028c6e638381928b3ec4252372
          cache: false